### ISSUE TITLE
allowStandaloneDeclarations does not apply to exported functions

### ISSUE THREAD

**Issue by neelance** [TristonJ/eslint-plugin-prefer-arrow#18]
Thanks for adding the `allowStandaloneDeclarations` option. However, this is still disallowed:
```ts
export function test() {
}
```
I think it should be allowed if `allowStandaloneDeclarations` is set.

**Comment by TristonJ** [comment]
This has been fixed in https://github.com/TristonJ/eslint-plugin-prefer-arrow/commit/67c1eb93246624b8cc4d3edeb61ad7815c23f62b

CommonJS style (`module.exports` and `exports`) as well as ESM style (`export` and `export default`) exports will now be allowed if using the `allowStandaloneDeclarations` option.

**Comment by neelance** [comment]
Thank you. It works well.
